#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Inventory.API/Inventory.API.csproj", "Inventory.API/"]
COPY ["Inventory.DataAccess/Inventory.DataAccess.csproj", "Inventory.DataAccess/"]
COPY ["Inventory.Core/Inventory.Core.csproj", "Inventory.Core/"]
COPY ["Inventory.ApplicationServices/Inventory.ApplicationServices.csproj", "Inventory.ApplicationServices/"]
COPY ["Inventory.ApplicationServices.Shared/Inventory.ApplicationServices.Shared.csproj", "Inventory.ApplicationServices.Shared/"]
RUN dotnet restore "Inventory.API/Inventory.API.csproj"
COPY . .
WORKDIR "/src/Inventory.API"
RUN dotnet build "Inventory.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Inventory.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Inventory.API.dll"]